version: '3.8'
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./bot:/usr/src/app:rw
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - TEST_ID=${TEST_ID}
    command: ["python3", "main.py"]
    tty: true
